### PR TITLE
added support for Metacritic and Awards properties

### PR DESCRIPTION
**Pull request by jpriebe**
I added support for Metacritic and Awards properties to the get() method's returned movie object.  They are mapped to the metacritic and awards properties (lowercased) for consistency with the other properties.

### CODE REVIEW

**Comment by misterhat** [comment]
This is now available under the latest module version (0.3.0) under the `metacritic` property and `awards` object with `wins` and `nomintations`. Check https://github.com/misterhat/omdb/commit/105e26ac04b9823ef10478bc05dc84b376388991.

**Comment by jpriebe** [comment]
Thanks for the merge.  I like what you're trying to do with the Awards, but I don't know if it will really capture what you think it will capture.  For example, the movie "Titanic" has this in its awards:

```
Won 11 Oscars. Another 116 wins & 63 nominations.
```

I believe your code would parse that into this:

```
awards: {
    wins: 116,
    nominations: 63
}
```

Technically, it should probably be

```
awards: {
    wins: 127,
    nominations: 63
}
```

but that just lumps the 11 Oscars in with 116 other random, mostly inconsequential awards.

The text could also have Oscar nominations, so it gets pretty complicated.

From what I've seen, by looking at a lot of these results, the wins and nominations don't really tell you much about the quality of the movie.  Lots of bad movies have random nominations for awards.  To me, the only thing that matters is the Oscar wins, and maybe the nominations.

If you really want to try to total up the wins and nominations, maybe you could do one of two things (or both):

- keep the full text
- break out the oscars separately

So it might look like this:

```
awards: {
    wins: 127,
    nominations: 63,
    text: "Won 11 Oscars. Another 116 wins & 63 nominations."
} 
```

or

```
awards: {
    oscar_wins: 11,
    oscar_nominations: 0,
    other_wins: 116,
    other_nominations: 63
} 
```

or even this:

```
awards: {
    oscar_wins: 11,
    oscar_nominations: 0,
    other_wins: 116,
    other_nominations: 63,
    text: "Won 11 Oscars. Another 116 wins & 63 nominations."
} 
```

What do you think?

**Comment by misterhat** [comment]
Why not:

````javascript
{
    wins: 127,
    nominations: 63,
    oscars: 11
}
````

?

This way it's pretty easy to get *just* oscars or subtract and find non-oscar wins. Is there a separate string for regular nomination vs oscar nomination?

**Comment by jpriebe** [comment]
Yes, there's a separate string for oscar nomination:

```
{
  "Title": "American Hustle",
  "Year": "2013",
  "Awards": "Nominated for 10 Oscars. Another 81 wins & 166 nominations.",
}
```

I don't think I've seen one where it lists "oscars won" and "oscars nominated".  So maybe if it wins one or more oscars, its nominations are lumped in with the other nominations.

I wish I knew more about how well-structured this formatting is.  I've looked at a few dozen of them, and they *seem* to be consistent, but I don't know how we could be 100% certain that they are all formatted the same way.

**Comment by jpriebe** [comment]
What's your call on the best way to handle this?  I've got an Amazon Alexa app that uses omdb, but I'm using my hacked version.  I'd love to bring it in line with your official version, but I really need those Oscar numbers separated out somehow (or if I can just get the OMDB raw text, that would be fine, too -- either way).

**Comment by misterhat** [comment]
I'll try contacting the author to get some information on the exact formatting of the string, but for now I'll implement the text property.

**Comment by jpriebe** [comment]
Thanks!  BTW -- how does the whole npm thing work?  In other words, when I do an 

```
npm install omdb
```

who decides what version I get?

**Comment by misterhat** [comment]
@jpriebe 
I'm actually unsure of the specifics, but if the nearest node_modules doesn't have the module then it will install the latest version.

Here is all the information I imagine is available for that command: https://docs.npmjs.com/cli/install

**Comment by jpriebe** [comment]
You're right -- I just tried to install, and it pulled your version 0.3.1.
Thanks!

**Pull request merged**
