### PR TITLE
Search terms object

### PR DESCRIPTION
**Pull request by grownseed**
This allows passing an object as search terms (strings are still handled). It also adds `type` and `y` (year) parameters.

### CODE REVIEW

**Comment by hikilaka** [comment]
I don't understand why the object's members are so vague. How is someone supposed to remember that the module uses y for year or s is for search (presumably)? Why wouldn't you just use their respective names?

**Comment by misterhat** [comment]
Can we do { terms: String, year: Number, type: String } instead?

**Comment by grownseed** [comment]
@hikilaka I guess this isn't ideal, but saying it's "so vague" might be a bit of an overstatement. I simply mapped the keys as specified on the [OMDB homepage](http://www.omdbapi.com/).

**Comment by hikilaka** [comment]
While that might make sense to someone who is familiar with working with OMDB, it might not to a newcomer. Using a single letter to denote a variable is not only bad practice but, again, vague.

**Comment by grownseed** [comment]
@hikilaka Like I mentioned in my previous comment, I'm happy to make the change when time allows. There is no need to be abrasive, we're all trying to help each other here. You're also more than welcome to submit your own changes.

**Comment by hikilaka** [comment]
Oh, don't take my comments the wrong way, please. I'm happy that you are contributing to this module! :-)

**Comment by misterhat** [comment]
Alright - the search terms object works with either verbose or omdb property names in the latest version.

**Comment by grownseed** [comment]
Guess I'm too late to the party :)

@misterhat I just pushed a commit to make parameters more explicit. There is also basic error handling, mostly to make sure OMDB doesn't get hit for no reason and that the user gets results within the expected `type`. Additionally, I made some slight updates to the docs.

**Pull request closed without merging**
